package crowdsourced.mturk;

import java.util.HashMap;
import java.util.Map;

/**
 * Contains a complete assignment. This is an answer to all the questions of the
 * corresponding HIT.
 *
 * @author Florian Chlan
 *
 */
public class Assignment {

    /**
     * The answers to the questions. Key: The unique identifier of the question.
     * Value: The answer to that particular question.
     */
    private Map<String, Answer> answers = new HashMap<String, Answer>();
    private HIT hit;

    /**
     * The unique assignment ID generated by AMT.
     */
    private String assignmentID;

    /**
     * Creates a new assignment
     *
     * @param hitArg
     *            The hit that this assignment belongs to.
     */
    public Assignment(HIT hitArg) {
        this.hit = hitArg;
    }

    /**
     * Returns a map of answers to the questions. Key: The unique identifier of
     * the question. Value: The answer to that particular question.
     *
     * @return A map of answers to the questions.
     */
    public Map<String, Answer> getAnswers() {
        return answers;
    }

    /**
     * @return The unique assignment ID generated by AMT.
     */
    public String getAssignmentID() {
        return assignmentID;
    }

    public void setAssignmentID(String assignmentId) {
        this.assignmentID = assignmentId;
    }

    public HIT getHit() {
        return hit;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result
                + ((assignmentID == null) ? 0 : assignmentID.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        Assignment other = (Assignment) obj;
        if (assignmentID == null) {
            if (other.assignmentID != null) {
                return false;
            }
        } else if (!assignmentID.equals(other.assignmentID)) {
            return false;
        }
        return true;
    }
}
